# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\cardEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from CustomDictionary import *
from Deck import *
class Ui_CardEdit(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(267, 256)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.topCardEdit = QtWidgets.QTextEdit(Form)
        self.topCardEdit.setObjectName("topCardEdit")
        self.verticalLayout.addWidget(self.topCardEdit)
        self.buttomCardEdit = QtWidgets.QTextEdit(Form)
        self.buttomCardEdit.setObjectName("buttomCardEdit")
        self.verticalLayout.addWidget(self.buttomCardEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveButton = QtWidgets.QPushButton(Form)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.saveButton.clicked.connect(lambda state:self.save())

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.fillUi()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.saveButton.setText(_translate("Form", "Save"))

    def __init__(self, card:Card, logger) -> None:
        #self.topCardEdit.setText(card.front_data)
        #self.buttomCardEdit.setText(card.back_data)
        self.card = card
        self.logger = logger
    
    def fillUi(self):

        self.topCardEdit.setText(self.card.front_data)
        self.buttomCardEdit.setText(self.card.back_data)

    def save(self):

        self.logger.info("Save button clicked, saving card")
        
        newCard = Card(
            front_data=self.topCardEdit.toPlainText().strip(),
            back_data=self.buttomCardEdit.toPlainText().strip(),
            date_added=self.card.date_added,
            id=self.card.id,
            parent_deck=self.card.parent_deck,
            order_in_deck=self.card.order_in_deck
        )

        self.card.parent_deck.modifyCard(self.card.genKey(), newCard)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_CardEdit()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
