# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\cardSearch.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from CustomDictionary import *
from Deck import *
import traceback
from cardEdit import Ui_CardEdit
class Ui_CardSearchWidget(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(268, 89)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchLineEdit = QtWidgets.QLineEdit(Form)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.horizontalLayout.addWidget(self.searchLineEdit)
        self.searchButton = QtWidgets.QPushButton(Form)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.searchButton.clicked.connect(lambda state:self.search())

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.searchButton.setText(_translate("Form", "Search"))

    def __init__(self, parent, MainWindow, logger, decks):
        self.parent = parent
        self.MainWindow = MainWindow
        self.logger = logger
        self.decks = decks

    def search(self):
        #self.logger.info("Searching for card")
        for deck in self.decks:
            try:
                self.logger.info("Searching for card " + "in deck " + deck.name)
                start = time.perf_counter()
                card = deck.searchCard(self.searchLineEdit.text())
                end = time.perf_counter()
                print("Time for search of key " + self.searchLineEdit.text() + ": " + str(end-start))
                
                try:
                    self.cardEdit = QtWidgets.QWidget() # Commits cardEdit to the namespace of the class so it will not be deleted
                    ui = Ui_CardEdit(card, self.logger)
                    ui.setupUi(self.cardEdit)
                    self.cardEdit.show()
                except Exception as e:
                    self.logger.error(traceback.format_exc())
            except EntryNotFound:
                self.logger.info("Card not found")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_CardSearchWidget()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
