# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\FlashCardAddWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from ast import Lambda
from PyQt5 import QtCore, QtGui, QtWidgets
from Deck import *

from Logger import MyLogger


class Ui_FlashCardAddWidget(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(240, 253)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout.addWidget(self.plainTextEdit_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addButton = QtWidgets.QPushButton(Form)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_2.addWidget(self.addButton)
        self.closeButton = QtWidgets.QPushButton(Form)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.addButton.clicked.connect(lambda x:self.addCard())

        # Populating combo box
        for deck in self.decks:
            self.comboBox.addItem(deck.name)

    def addCard(self):
        deck_index = self.comboBox.currentIndex()
        top = self.plainTextEdit.toPlainText()
        bottom = self.plainTextEdit_2.toPlainText()

        self.decks[deck_index].addCard(Card(
            front_data=top,
            back_data=bottom,
            date_added="something",
            parent_deck = self.decks[deck_index],
            order_in_deck = len(self.decks[deck_index].cards)+1,
            id=1
        )
        )

        self.plainTextEdit.clear()
        self.plainTextEdit_2.clear()

    def __init__(self, parent, logger:MyLogger, decks) -> None:
        
        self.parent = parent

        self.logger = logger

        self.decks = decks

        self.logger.info("Initializing FlashCardAddWidget")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Deck:"))
        self.addButton.setText(_translate("Form", "Add"))
        self.closeButton.setText(_translate("Form", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_FlashCardAddWidget()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
