# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\StudySelectDiolog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StudySelectDiolog(object):
    def setupUi(self, StudySelectDiolog):
        StudySelectDiolog.setObjectName("StudySelectDiolog")
        StudySelectDiolog.resize(320, 106)
        self.buttonBox = QtWidgets.QDialogButtonBox(StudySelectDiolog)
        self.buttonBox.setGeometry(QtCore.QRect(-40, 60, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(StudySelectDiolog)
        self.label.setGeometry(QtCore.QRect(10, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.deckComboBox = QtWidgets.QComboBox(StudySelectDiolog)
        self.deckComboBox.setGeometry(QtCore.QRect(150, 30, 151, 22))
        self.deckComboBox.setObjectName("deckComboBox")

        self.retranslateUi(StudySelectDiolog)
        self.buttonBox.accepted.connect(StudySelectDiolog.accept)
        self.buttonBox.rejected.connect(StudySelectDiolog.reject)
        QtCore.QMetaObject.connectSlotsByName(StudySelectDiolog)

    def retranslateUi(self, StudySelectDiolog):
        _translate = QtCore.QCoreApplication.translate
        StudySelectDiolog.setWindowTitle(_translate("StudySelectDiolog", "Dialog"))
        self.label.setText(_translate("StudySelectDiolog", "Choose a Deck:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StudySelectDiolog = QtWidgets.QDialog()
    ui = Ui_StudySelectDiolog()
    ui.setupUi(StudySelectDiolog)
    StudySelectDiolog.show()
    sys.exit(app.exec_())
